version: '3'

services:
  php:
    container_name: web
    hostname: web
    image: php:7.2-apache
    build: .
    restart: "no" # unless-stopped
    depends_on: 
      - mysql
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    networks:
      - db_web
    extra_hosts:
      - "dockerhost:172.17.0.1"


  mysql:
    container_name: db
    image: mysql:5.7
    restart: "no" # unless-stopped
    volumes:
      - ./data_db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - db_adm
      - db_web

  phpmyadmin:
    container_name: adm
    image: phpmyadmin/phpmyadmin
    restart: "no" # unless-stopped
    ports:
      - 8091:80
    environment:
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=123456
    networks:
      - db_adm

networks:
  db_adm:
  db_web: